import { onAuthStateChanged, signOut } from 'firebase/auth';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux';
import Header from '../components/Header';
import { logout, selectUser } from '../features/userSlice';
import { auth } from '../lib/firebase';

const Profile = () => {
    const user = useSelector(selectUser);
    const router = useRouter();
  const dispatch =  useDispatch()
     useEffect(() => {
       onAuthStateChanged(auth, (user) => {
         if (user) {
           dispatch(
             login({
               uid: user.uid,
               email: user.email,
             })
           );
         } else {
           dispatch(logout);
           router.push("/");
         }
       });
     }, [onAuthStateChanged]);
  return (
    <div className="bg-black min-h-screen text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {user ? (
        <div className="flex flex-col w-3/2 mx-auto pt-[8%] max-w-3xl">
          <h1 className="text-6xl font-normal border-b border-[#282c2d] mb-3">
            Edit Profile
          </h1>
          <div className="flex">
            <img
              src="https://imgix.bustle.com/uploads/image/2017/8/29/c8c8077a-10fc-44d5-93f0-da4e592a299e-netflix-logo-print_pms.jpg?w=800&fit=crop&crop=faces&auto=format%2Ccompress"
              alt=""
              className="h-[100px]"
            />
            <div className="ml-6 flex-1">
              <h2 className="bg-gray-600 p-4 text-base pl-5">{user?.email}</h2>
              <div className="px-3 py-4 text-base w-full mt-[5%] max-w-3xl justify-center items-center border-none cursor-pointer bg-[#e50914]">
                <button onClick={()=> signOut(auth)}>Sign Out</button>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="flex flex-col w-3/2 mx-auto pt-[8%] max-w-3xl">
          <h1 className="text-3xl font-normal border-b border-[#282c2d] mb-3">
           You are not Logged In!
                      </h1>
                      <button onClick={()=> router.push('/')} className="px-1 py-6 text-base w-full mt-[5%] max-w-3xl justify-center items-center border-none cursor-pointer bg-[#e50914]"> Return To Login Page
            </button>
        </div>
      )}
    </div>
  );
}

export default Profile
